"use client"
import './globals.css'
import { Inter,Poppins } from 'next/font/google'

import React from 'react' 
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({ subsets:['latin']  , weight :['300','400' , '700']})
export const metadata = {
  title: 'Vincent Project',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en">
      <body className={(poppins.className)}>{children}</body>
    </html>
  )
}
